package CQRS.Generation.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ApplicationSide extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ApplicationSide() {
    super(0x273bc31819694c83L, 0x8484525ea753e78bL, 0x2cd9954889e49a89L, "ApplicationSide", "r:7c81c792-29f8-43b8-86dd-c441406afee9(CQRS.Generation.structure)/3231778346398685833");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_COMMAND_SIDE_0 = new EnumerationDescriptor.MemberDescriptor("COMMAND_SIDE", "COMMAND_SIDE", 0x2cd9954889e49a8aL, "r:7c81c792-29f8-43b8-86dd-c441406afee9(CQRS.Generation.structure)/3231778346398685834");
  private final EnumerationDescriptor.MemberDescriptor myMember_QUERY_SIDE_0 = new EnumerationDescriptor.MemberDescriptor("QUERY_SIDE", "QUERY_SIDE", 0x2cd9954889e49a8bL, "r:7c81c792-29f8-43b8-86dd-c441406afee9(CQRS.Generation.structure)/3231778346398685835");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x273bc31819694c83L, 0x8484525ea753e78bL, 0x2cd9954889e49a89L, 0x2cd9954889e49a8aL, 0x2cd9954889e49a8bL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_COMMAND_SIDE_0, myMember_QUERY_SIDE_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "COMMAND_SIDE":
        return myMember_COMMAND_SIDE_0;
      case "QUERY_SIDE":
        return myMember_QUERY_SIDE_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
