package CQRS.Kotlin.generation;

/*Generated by MPS */

import CQRS.Generation.generation.DependencyResolver;
import org.jetbrains.mps.openapi.model.SNode;
import CQRS.Generation.generation.GenerationTarget;

public class KotlinDependencyResolver implements DependencyResolver {

  private SNode boundedContext;

  public KotlinDependencyResolver(SNode context) {
    this.boundedContext = context;
  }

  @Override
  public SNode getBoundedContext() {
    return boundedContext;
  }

  @Override
  public GenerationTarget getGenerationTarget() {
    return GenerationTarget.KOTLIN;
  }

}
