package CQRS.helper;

/*Generated by MPS */

import java.awt.Color;
import jetbrains.mps.util.Pair;

public class KeywordColorUtils {

  private static final Color KEYWORD_LIGHT_COLOR = new Color(207, 132, 10);
  private static final Color KEYWORD_DARK_COLOR = new Color(207, 132, 10);

  private static final Color OPTIONAL_KEYWORD_LIGHT_COLOR = new Color(255, 137, 117);
  private static final Color OPTIONAL_KEYWORD_DARK_COLOR = new Color(124, 85, 85);

  private static final Color GENERIC_TYPE_LIGHT_COLOR = new Color(255, 200, 0);
  private static final Color GENERIC_TYPE_DARK_COLOR = new Color(255, 200, 0);

  private static final Color PRIMITIVE_TYPE_LIGHT_COLOR = new Color(144, 111, 159);
  private static final Color PRIMITIVE_TYPE_DARK_COLOR = new Color(159, 101, 8);

  private static final Color COLLECTION_TYPE_LIGHT_COLOR = new Color(88, 157, 246);
  private static final Color COLLECTION_TYPE_DARK_COLOR = new Color(88, 157, 246);

  private static final Color BOUNDED_CONTEXT_LIGHT_COLOR = new Color(107, 67, 249);
  private static final Color BOUNDED_CONTEXT_DARK_COLOR = new Color(151, 118, 169);

  private static final Color CONNECTING_COMPONENT_LIGHT_COLOR = new Color(137, 137, 0);
  private static final Color CONNECTING_COMPONENT_DARK_COLOR = new Color(137, 137, 0);

  private static final Color COMMAND_COMPONENT_LIGHT_COLOR = new Color(98, 150, 85);
  private static final Color COMMAND_COMPONENT_DARK_COLOR = new Color(98, 150, 85);

  private static final Color QUERY_COMPONENT_LIGHT_COLOR = new Color(0, 137, 137);
  private static final Color QUERY_COMPONENT_DARK_COLOR = new Color(0, 137, 137);


  public static Pair<Color, Color> getKeywordColors() {
    return new Pair<>(KEYWORD_LIGHT_COLOR, KEYWORD_DARK_COLOR);
  }

  public static Pair<Color, Color> getOptionalKeywordColors() {
    return new Pair<>(OPTIONAL_KEYWORD_LIGHT_COLOR, OPTIONAL_KEYWORD_DARK_COLOR);
  }

  public static Pair<Color, Color> getGenericTypeColors() {
    return new Pair<>(GENERIC_TYPE_LIGHT_COLOR, GENERIC_TYPE_DARK_COLOR);
  }

  public static Pair<Color, Color> getPrimitiveTypeColors() {
    return new Pair<>(PRIMITIVE_TYPE_LIGHT_COLOR, PRIMITIVE_TYPE_DARK_COLOR);
  }

  public static Pair<Color, Color> getCollectionTypeColors() {
    return new Pair<>(COLLECTION_TYPE_LIGHT_COLOR, COLLECTION_TYPE_DARK_COLOR);
  }

  public static Pair<Color, Color> getBoundedContextColors() {
    return new Pair<>(BOUNDED_CONTEXT_LIGHT_COLOR, BOUNDED_CONTEXT_DARK_COLOR);
  }

  public static Pair<Color, Color> getConnectingComponentColors() {
    return new Pair<>(CONNECTING_COMPONENT_LIGHT_COLOR, CONNECTING_COMPONENT_DARK_COLOR);
  }

  public static Pair<Color, Color> getCommandComponentColors() {
    return new Pair<>(COMMAND_COMPONENT_LIGHT_COLOR, COMMAND_COMPONENT_DARK_COLOR);
  }

  public static Pair<Color, Color> getQueryComponentColors() {
    return new Pair<>(QUERY_COMPONENT_LIGHT_COLOR, QUERY_COMPONENT_DARK_COLOR);
  }

}
