package CQRS.actions;

/*Generated by MPS */

import jetbrains.mps.openapi.actions.descriptor.PastePostProcessor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.model.SNode;
import CQRS.behavior.IComponentWithRepositoryReferences__BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public final class CopyPasteHandlers_PastePostProcessor_1 implements PastePostProcessor {
  @Override
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.Event$7G;
  }
  @Override
  public void postProcessNode(SNode pastedNode) {
    IComponentWithRepositoryReferences__BehaviorDescriptor.onPastedInParentComponentWithRepositoryReferences_idomljbxlS61.invoke(pastedNode);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Event$7G = MetaAdapterFactory.getConcept(0xfe04f903cef2451dL, 0x9401426cad0a8857L, 0x73da5086440e2438L, "CQRS.structure.Event");
  }
}
