package CQRS.actions;

/*Generated by MPS */

import jetbrains.mps.openapi.actions.descriptor.PasteWrapper;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.model.SNode;
import CQRS.behavior.Query__BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public final class PasteWrappers_PasteWrapper_4 implements PasteWrapper {
  @Override
  public SAbstractConcept getSourceConcept() {
    return CONCEPTS.Query$nF;
  }
  @Override
  public SAbstractConcept getTargetConcept() {
    return CONCEPTS.QueryReference$zj;
  }
  @Override
  public SNode wrap(SNode sourceNode) {
    // TODO Das geht irgendwie noch nicht
    return (SNode) Query__BehaviorDescriptor.toReference_id5jZDGThYDzO.invoke(sourceNode);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Query$nF = MetaAdapterFactory.getConcept(0xfe04f903cef2451dL, 0x9401426cad0a8857L, 0x73da5086440e2444L, "CQRS.structure.Query");
    /*package*/ static final SConcept QueryReference$zj = MetaAdapterFactory.getConcept(0xfe04f903cef2451dL, 0x9401426cad0a8857L, 0x73da5086440e2447L, "CQRS.structure.QueryReference");
  }
}
