package CQRS.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_VariableModifier extends EnumerationDescriptorBase {

  public EnumerationDescriptor_VariableModifier() {
    super(0xfe04f903cef2451dL, 0x9401426cad0a8857L, 0x6443e2542ec484fL, "VariableModifier", "r:8c31c3a3-db83-4ac9-834b-2cb8f0f4a7eb(CQRS.structure)/451554192401385551");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_public_0 = new EnumerationDescriptor.MemberDescriptor("public", "public", 0x6443e2542ec4851L, "r:8c31c3a3-db83-4ac9-834b-2cb8f0f4a7eb(CQRS.structure)/451554192401385553");
  private final EnumerationDescriptor.MemberDescriptor myMember_private_0 = new EnumerationDescriptor.MemberDescriptor("private", "private", 0x6443e2542ec4850L, "r:8c31c3a3-db83-4ac9-834b-2cb8f0f4a7eb(CQRS.structure)/451554192401385552");
  private final EnumerationDescriptor.MemberDescriptor myMember_protected_0 = new EnumerationDescriptor.MemberDescriptor("protected", "protected", 0x6443e2542ec4854L, "r:8c31c3a3-db83-4ac9-834b-2cb8f0f4a7eb(CQRS.structure)/451554192401385556");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xfe04f903cef2451dL, 0x9401426cad0a8857L, 0x6443e2542ec484fL, 0x6443e2542ec4851L, 0x6443e2542ec4850L, 0x6443e2542ec4854L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_public_0, myMember_private_0, myMember_protected_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_public_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "public":
        return myMember_public_0;
      case "private":
        return myMember_private_0;
      case "protected":
        return myMember_protected_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
