package CQRS.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_DtoDataTypeRuleApplicability extends EnumerationDescriptorBase {

  public EnumerationDescriptor_DtoDataTypeRuleApplicability() {
    super(0xfe04f903cef2451dL, 0x9401426cad0a8857L, 0x3c4795ac30c0ec15L, "DtoDataTypeRuleApplicability", "r:8c31c3a3-db83-4ac9-834b-2cb8f0f4a7eb(CQRS.structure)/4343604932406995989");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Exact_0 = new EnumerationDescriptor.MemberDescriptor("Exact", "exact", 0x3c4795ac30c0ec16L, "r:8c31c3a3-db83-4ac9-834b-2cb8f0f4a7eb(CQRS.structure)/4343604932406995990");
  private final EnumerationDescriptor.MemberDescriptor myMember_Partial_0 = new EnumerationDescriptor.MemberDescriptor("Partial", "partial", 0x3c4795ac30c0ec17L, "r:8c31c3a3-db83-4ac9-834b-2cb8f0f4a7eb(CQRS.structure)/4343604932406995991");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xfe04f903cef2451dL, 0x9401426cad0a8857L, 0x3c4795ac30c0ec15L, 0x3c4795ac30c0ec16L, 0x3c4795ac30c0ec17L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Exact_0, myMember_Partial_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_Exact_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Exact":
        return myMember_Exact_0;
      case "Partial":
        return myMember_Partial_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
