package CQRS.util;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import java.util.Objects;
import jetbrains.mps.openapi.editor.cells.EditorCell_Collection;

public class EditorContextUtils {

  public static boolean isSelectedCellChildOf(EditorContext context, String parentCellId) {
    EditorCell selectedCell = context.getSelectedCell();
    if (Objects.equals(selectedCell, null)) {
      return false;
    }

    if (Objects.equals(selectedCell.getCellId(), parentCellId)) {
      return true;
    }

    EditorCell_Collection parent = selectedCell.getParent();

    while (!(Objects.equals(parent, null))) {
      if (Objects.equals(parent.getCellId(), parentCellId)) {
        return true;
      }
      parent = parent.getParent();
    }

    return false;
  }

}
