package CQRS.Generation.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;

public abstract class CqrsTextGenComponents {
  public static void onNewLine(String text, final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append(text);
    tgs.newLine();
  }
  public static void indent(int count, final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    for (int i = 0; i < count; i++) {
      tgs.indent();
    }
  }
  public static void newLine(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.newLine();
  }
  public static void newLines(int count, final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    for (int i = 0; i < count; i++) {
      CqrsTextGenComponents.newLine(ctx);
    }
  }
}
