package CQRS.Kotlin.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import CQRS.Generation.generation.DependencyUtils;
import CQRS.Generation.textGen.CqrsTextGenComponents;

public class AggregateIdRepositoryInterfaceKotlinOutput_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    String className = DependencyUtils.AGGREGATE_ID_REPOSITORY_INTERFACE_NAME;
    String aggregateInterfaceName = DependencyUtils.AGGREGATE_INTERFACE_NAME;
    String repositoryInterfaceName = DependencyUtils.AGGREGATE_REPOSITORY_INTERFACE_NAME;

    KotlinTextGenComponents.header(ctx.getPrimaryInput(), ctx);

    KotlinTextGenComponents._interface(className, ctx);
    tgs.append("<ID, Aggregate:  ");
    tgs.append(aggregateInterfaceName);
    tgs.append("<ID>>:");
    tgs.append(repositoryInterfaceName);
    tgs.append("<Aggregate> {");
    CqrsTextGenComponents.newLine(ctx);
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.increaseIndent();
    tgs.append("fun getById(id: ID): Aggregate");
    CqrsTextGenComponents.newLine(ctx);
    tgs.decreaseIndent();
    ctx.getBuffer().area().decreaseIndent();
    tgs.append("}");
  }
}
