package CQRS.Kotlin.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import CQRS.Generation.generation.DependencyUtils;
import CQRS.Generation.textGen.CqrsTextGenComponents;

public class AggregateRepositoryInterfaceKotlinOutput_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    KotlinTextGenComponents.header(ctx.getPrimaryInput(), ctx);

    KotlinTextGenComponents._interface(DependencyUtils.AGGREGATE_REPOSITORY_INTERFACE_NAME, ctx);
    tgs.append("<Aggregate: AggregateRoot<*>> {");
    CqrsTextGenComponents.newLines(2, ctx);
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("fun save(aggregate: Aggregate)");
    CqrsTextGenComponents.newLines(2, ctx);
    tgs.indent();
    tgs.append("fun add(aggregate: Aggregate)");
    CqrsTextGenComponents.newLines(2, ctx);
    ctx.getBuffer().area().decreaseIndent();
    tgs.append("}");
  }
}
