package CQRS.Kotlin.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import CQRS.Kotlin.behavior.KotlinElementOutput__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class IDataTypeKotlinOutput_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append(KotlinElementOutput__BehaviorDescriptor.converter_id2Np_kya0nph.invoke(ctx.getPrimaryInput()).convertType(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.type$7Mnf)));
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink type$7Mnf = MetaAdapterFactory.getReferenceLink(0x273bc31819694c83L, 0x8484525ea753e78bL, 0x48bafb85c0476f12L, 0x48bafb85c0476f13L, "type");
  }
}
