package CQRS.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class IQueryGenerationSettingsComponent_Constraints extends BaseConstraintsDescriptor {
  public IQueryGenerationSettingsComponent_Constraints() {
    super(CONCEPTS.IQueryGenerationSettingsComponent$su);
  }

  @Override
  public SConcept getDefaultConcreteConcept() {
    return CONCEPTS.EmptyLine$_9;
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept IQueryGenerationSettingsComponent$su = MetaAdapterFactory.getInterfaceConcept(0xfe04f903cef2451dL, 0x9401426cad0a8857L, 0x56a1ac122ac59248L, "CQRS.structure.IQueryGenerationSettingsComponent");
    /*package*/ static final SConcept EmptyLine$_9 = MetaAdapterFactory.getConcept(0xfe04f903cef2451dL, 0x9401426cad0a8857L, 0x62cb964344649a2L, "CQRS.structure.EmptyLine");
  }
}
