package CQRS.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintFunction;
import jetbrains.mps.smodel.runtime.ConstraintContext_DefaultScopeProvider;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.scope.EmptyScope;
import jetbrains.mps.scope.ListScope;
import CQRS.behavior.BoundedContext__BehaviorDescriptor;
import CQRS.behavior.IElementOfBoundedContext__BehaviorDescriptor;
import java.util.Objects;
import CQRS.behavior.IDtoDerivableReference__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import CQRS.behavior.IDtoDerivation__BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class ValueObject_Constraints extends BaseConstraintsDescriptor {
  public ValueObject_Constraints() {
    super(CONCEPTS.ValueObject$iv);
  }

  @Override
  public ConstraintFunction<ConstraintContext_DefaultScopeProvider, ReferenceScopeProvider> calculateDefaultScopeConstraint() {
    return new ConstraintFunction<ConstraintContext_DefaultScopeProvider, ReferenceScopeProvider>() {
      @Nullable
      public ReferenceScopeProvider invoke(@NotNull ConstraintContext_DefaultScopeProvider context, @Nullable CheckingNodeContext checkingNodeContext) {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return new SNodePointer("r:0d7993a3-d2b8-4ac6-8b11-a4cb9134a9ef(CQRS.constraints)", "8348073396877426389");
          }
          @Override
          public Scope createScope(final ReferenceConstraintsContext _context) {
            SNode component = SNodeOperations.getNodeAncestor(_context.getContextNode(), CONCEPTS.IBoundedContextComponent$2H, true, false);
            {
              final SNode valueObject = component;
              if (SNodeOperations.isInstanceOf(valueObject, CONCEPTS.ValueObject$iv)) {
                return ValueObject_Constraints.this._additional_provideValueObjectScope(valueObject);
              }
            }
            {
              final SNode entity = component;
              if (SNodeOperations.isInstanceOf(entity, CONCEPTS.Entity$lp)) {
                return ValueObject_Constraints.this._additional_provideEntityScope(entity);
              }
            }
            {
              final SNode aggregateRoot = component;
              if (SNodeOperations.isInstanceOf(aggregateRoot, CONCEPTS.AggregateRoot$Q_)) {
                return ValueObject_Constraints.this._additional_provideAggregateRootScope(aggregateRoot);
              }
            }
            {
              final SNode repository = component;
              if (SNodeOperations.isInstanceOf(repository, CONCEPTS.AggregateRootRepository$qW)) {
                return ValueObject_Constraints.this._additional_provideAggregateRootRepositoryScope(repository);
              }
            }
            {
              final SNode dto = component;
              if (SNodeOperations.isInstanceOf(dto, CONCEPTS.Dto$yu)) {
                return ValueObject_Constraints.this._additional_provideDtoScope(dto, _context.getContextNode());
              }
            }
            {
              final SNode flatteningRuleContainer = component;
              if (SNodeOperations.isInstanceOf(flatteningRuleContainer, CONCEPTS.DtoFlatteningRuleContainer$qJ)) {
                return ValueObject_Constraints.this._additional_provideDtoFlatteningRuleScope(flatteningRuleContainer, _context.getContextNode());
              }
            }

            return new EmptyScope();
          }
        };
      }
    };
  }
  private Scope _additional_provideValueObjectScope(SNode valueObject) {
    return ListScope.forNamedElements(BoundedContext__BehaviorDescriptor.valueObjects_id7fqk8p3Ma$i.invoke(IElementOfBoundedContext__BehaviorDescriptor.boundedContext_id3VGLvhEO$iA.invoke(valueObject)));
  }
  private Scope _additional_provideEntityScope(SNode entity) {
    return ListScope.forNamedElements(BoundedContext__BehaviorDescriptor.valueObjects_id7fqk8p3Ma$i.invoke(IElementOfBoundedContext__BehaviorDescriptor.boundedContext_id3VGLvhEO$iA.invoke(entity)));
  }
  private Scope _additional_provideAggregateRootScope(SNode aggregateRoot) {
    return ListScope.forNamedElements(BoundedContext__BehaviorDescriptor.valueObjects_id7fqk8p3Ma$i.invoke(IElementOfBoundedContext__BehaviorDescriptor.boundedContext_id3VGLvhEO$iA.invoke(aggregateRoot)));
  }
  private Scope _additional_provideAggregateRootRepositoryScope(SNode repository) {
    return ListScope.forNamedElements(BoundedContext__BehaviorDescriptor.valueObjects_id7fqk8p3Ma$i.invoke(IElementOfBoundedContext__BehaviorDescriptor.boundedContext_id3VGLvhEO$iA.invoke(repository)));
  }
  private Scope _additional_provideDtoScope(SNode dto, SNode contextNode) {
    if (contextNode == dto || Objects.equals(SNodeOperations.getContainingLink(contextNode), LINKS.derivableReference$gfNO)) {
      SNode boundedContext = IElementOfBoundedContext__BehaviorDescriptor.boundedContext_id3VGLvhEO$iA.invoke(dto);
      return ListScope.forNamedElements(BoundedContext__BehaviorDescriptor.findUnusedDtoDerivablesIncluding_id3NXs7yo7EMe.invoke(boundedContext, IDtoDerivableReference__BehaviorDescriptor.getDtoDerivable_id4LpUh3T0tIy.invoke(SLinkOperations.getTarget(dto, LINKS.derivableReference$gfNO))));
    }

    return new EmptyScope();
  }
  private Scope _additional_provideDtoFlatteningRuleScope(SNode flatteningRuleContainer, SNode contextNode) {
    SNode flatteningRule = SNodeOperations.getNodeAncestor(contextNode, CONCEPTS.DtoFlatteningRule$GR, true, false);

    if (contextNode == flatteningRule || Objects.equals(SNodeOperations.getContainingLink(contextNode), LINKS.derivableReference$gfNO)) {
      SNode boundedContext = IElementOfBoundedContext__BehaviorDescriptor.boundedContext_id3VGLvhEO$iA.invoke(flatteningRuleContainer);
      return ListScope.forNamedElements(BoundedContext__BehaviorDescriptor.findUnusedDtoDerivablesForFlatteningRulesIncluding_id3NXs7yowktH.invoke(boundedContext, IDtoDerivation__BehaviorDescriptor.getDtoDerivable_id3NXs7yomd17.invoke(flatteningRule)));
    }

    return new EmptyScope();
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ValueObject$iv = MetaAdapterFactory.getConcept(0xfe04f903cef2451dL, 0x9401426cad0a8857L, 0x4f0a0db9ac16f8f7L, "CQRS.structure.ValueObject");
    /*package*/ static final SInterfaceConcept IBoundedContextComponent$2H = MetaAdapterFactory.getInterfaceConcept(0xfe04f903cef2451dL, 0x9401426cad0a8857L, 0x6375c6ceebab8368L, "CQRS.structure.IBoundedContextComponent");
    /*package*/ static final SConcept Entity$lp = MetaAdapterFactory.getConcept(0xfe04f903cef2451dL, 0x9401426cad0a8857L, 0x4f0a0db9ac16f8fdL, "CQRS.structure.Entity");
    /*package*/ static final SConcept AggregateRoot$Q_ = MetaAdapterFactory.getConcept(0xfe04f903cef2451dL, 0x9401426cad0a8857L, 0x4cfae7e929829c99L, "CQRS.structure.AggregateRoot");
    /*package*/ static final SConcept AggregateRootRepository$qW = MetaAdapterFactory.getConcept(0xfe04f903cef2451dL, 0x9401426cad0a8857L, 0x73da5086441fb19dL, "CQRS.structure.AggregateRootRepository");
    /*package*/ static final SConcept Dto$yu = MetaAdapterFactory.getConcept(0xfe04f903cef2451dL, 0x9401426cad0a8857L, 0x4f0a0db9ac16f903L, "CQRS.structure.Dto");
    /*package*/ static final SConcept DtoFlatteningRuleContainer$qJ = MetaAdapterFactory.getConcept(0xfe04f903cef2451dL, 0x9401426cad0a8857L, 0x3cfd70789940548dL, "CQRS.structure.DtoFlatteningRuleContainer");
    /*package*/ static final SConcept DtoFlatteningRule$GR = MetaAdapterFactory.getConcept(0xfe04f903cef2451dL, 0x9401426cad0a8857L, 0x12da95fb99e0f985L, "CQRS.structure.DtoFlatteningRule");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink derivableReference$gfNO = MetaAdapterFactory.getContainmentLink(0xfe04f903cef2451dL, 0x9401426cad0a8857L, 0x3cfd70789857e2b7L, 0x3cfd707898583364L, "derivableReference");
  }
}
